# Generated by Django 5.2.17 on 2026-08-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(help_text="AEMET station indicativo, e.g. '89070'.", max_length=10)),
                ('timestamp', models.DateTimeField(help_text='Observation datetime, stored in UTC.')),
                ('temperature', models.FloatField(blank=True, help_text='Temperature in °C.', null=True)),
                ('pressure', models.FloatField(blank=True, help_text='Pressure in hPa.', null=True)),
                ('speed', models.FloatField(blank=True, help_text='Wind speed in m/s.', null=True)),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['station', 'timestamp'], name='weather_mea_station_99f884_idx')],
                'constraints': [models.UniqueConstraint(fields=('station', 'timestamp'), name='unique_station_timestamp')],
            },
        ),
    ]
